//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_language() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.fr_language", typeof(fr_language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail de sauvegarde supprimé.
        /// </summary>
        internal static string backup_deleted {
            get {
                return ResourceManager.GetString("backup_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution de .
        /// </summary>
        internal static string backup_execution {
            get {
                return ResourceManager.GetString("backup_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde terminé.
        /// </summary>
        internal static string backup_execution_finished {
            get {
                return ResourceManager.GetString("backup_execution_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à différentiel.
        /// </summary>
        internal static string backuptype_differential {
            get {
                return ResourceManager.GetString("backuptype_differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à complet.
        /// </summary>
        internal static string backuptype_full {
            get {
                return ResourceManager.GetString("backuptype_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        internal static string backupview_back {
            get {
                return ResourceManager.GetString("backupview_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail de sauvegarde créé.
        /// </summary>
        internal static string backupview_backup_created {
            get {
                return ResourceManager.GetString("backupview_backup_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string backupview_delete_backup {
            get {
                return ResourceManager.GetString("backupview_delete_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string backupview_edit_backup {
            get {
                return ResourceManager.GetString("backupview_edit_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter la sauvegarde.
        /// </summary>
        internal static string backupview_execute_backup {
            get {
                return ResourceManager.GetString("backupview_execute_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau nom du travail de sauvegarde : .
        /// </summary>
        internal static string backupview_rename {
            get {
                return ResourceManager.GetString("backupview_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail de sauvegarde sélectionné : .
        /// </summary>
        internal static string backupview_selected_backup_name {
            get {
                return ResourceManager.GetString("backupview_selected_backup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source : .
        /// </summary>
        internal static string backupview_selected_backup_source {
            get {
                return ResourceManager.GetString("backupview_selected_backup_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination : .
        /// </summary>
        internal static string backupview_selected_backup_target {
            get {
                return ResourceManager.GetString("backupview_selected_backup_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type : .
        /// </summary>
        internal static string backupview_selected_backup_type {
            get {
                return ResourceManager.GetString("backupview_selected_backup_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez une action : .
        /// </summary>
        internal static string chose_action {
            get {
                return ResourceManager.GetString("chose_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentiel.
        /// </summary>
        internal static string DIFFERENTIAL {
            get {
                return ResourceManager.GetString("DIFFERENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la sauvegarde.
        /// </summary>
        internal static string error_backup {
            get {
                return ResourceManager.GetString("error_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les champs n&apos;ont pas été remplies.
        /// </summary>
        internal static string error_fields_empty {
            get {
                return ResourceManager.GetString("error_fields_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action impossible.
        /// </summary>
        internal static string error_impossible_action {
            get {
                return ResourceManager.GetString("error_impossible_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom déjà utilisé.
        /// </summary>
        internal static string error_name_already_used {
            get {
                return ResourceManager.GetString("error_name_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de travail de sauvegarde inconnu.
        /// </summary>
        internal static string error_unknown_type {
            get {
                return ResourceManager.GetString("error_unknown_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complet.
        /// </summary>
        internal static string FULL {
            get {
                return ResourceManager.GetString("FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        internal static string mainview_back {
            get {
                return ResourceManager.GetString("mainview_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux de sauvegarde.
        /// </summary>
        internal static string mainview_backupworks {
            get {
                return ResourceManager.GetString("mainview_backupworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez le nom de la sauvegarde : .
        /// </summary>
        internal static string mainview_create_backup_name {
            get {
                return ResourceManager.GetString("mainview_create_backup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez le répertoire source : .
        /// </summary>
        internal static string mainview_create_backup_source {
            get {
                return ResourceManager.GetString("mainview_create_backup_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez le répertoire cible : .
        /// </summary>
        internal static string mainview_create_backup_target {
            get {
                return ResourceManager.GetString("mainview_create_backup_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez le type de sauvegarde (complet / différentiel) : .
        /// </summary>
        internal static string mainview_create_backup_type {
            get {
                return ResourceManager.GetString("mainview_create_backup_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un travail de sauvegarde.
        /// </summary>
        internal static string mainview_create_backup_work {
            get {
                return ResourceManager.GetString("mainview_create_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter tous les travaux de sauvegarde.
        /// </summary>
        internal static string mainview_execute_all_backup_works {
            get {
                return ResourceManager.GetString("mainview_execute_all_backup_works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue définit en Français.
        /// </summary>
        internal static string mainview_language_changed {
            get {
                return ResourceManager.GetString("mainview_language_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration de la langue.
        /// </summary>
        internal static string mainview_language_configuration {
            get {
                return ResourceManager.GetString("mainview_language_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string mainview_language_en {
            get {
                return ResourceManager.GetString("mainview_language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string mainview_language_fr {
            get {
                return ResourceManager.GetString("mainview_language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        internal static string mainview_quit {
            get {
                return ResourceManager.GetString("mainview_quit", resourceCulture);
            }
        }
    }
}
