//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_language() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.fr_language", typeof(fr_language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à complet.
        /// </summary>
        internal static string backuptype_full {
            get {
                return ResourceManager.GetString("backuptype_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer une sauvegarde.
        /// </summary>
        internal static string create_backup {
            get {
                return ResourceManager.GetString("create_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentiel.
        /// </summary>
        internal static string DIFFERENTIAL {
            get {
                return ResourceManager.GetString("DIFFERENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension à chiffrer.
        /// </summary>
        internal static string encrypted_extension {
            get {
                return ResourceManager.GetString("encrypted_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        internal static string encrypted_extension_add {
            get {
                return ResourceManager.GetString("encrypted_extension_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string encrypted_extension_delete {
            get {
                return ResourceManager.GetString("encrypted_extension_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pack://application:,,,/Resources/FlagEnglish.png.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les champs n&apos;ont pas été remplies.
        /// </summary>
        internal static string error_fields_empty {
            get {
                return ResourceManager.GetString("error_fields_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom déjà utilisé.
        /// </summary>
        internal static string error_name_already_used {
            get {
                return ResourceManager.GetString("error_name_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de travail de sauvegarde inconnu.
        /// </summary>
        internal static string error_unknown_type {
            get {
                return ResourceManager.GetString("error_unknown_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pack://application:,,,/Resources/FlagFrench.png.
        /// </summary>
        internal static string flag_name {
            get {
                return ResourceManager.GetString("flag_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pack://application:,,,/Resources/FlagFrench.png.
        /// </summary>
        internal static string FRENCH {
            get {
                return ResourceManager.GetString("FRENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complet.
        /// </summary>
        internal static string FULL {
            get {
                return ResourceManager.GetString("FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les informations.
        /// </summary>
        internal static string get_info {
            get {
                return ResourceManager.GetString("get_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de sauvegarde.
        /// </summary>
        internal static string label_backup_name {
            get {
                return ResourceManager.GetString("label_backup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde.
        /// </summary>
        internal static string label_backup_type {
            get {
                return ResourceManager.GetString("label_backup_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire Source.
        /// </summary>
        internal static string label_source_directory {
            get {
                return ResourceManager.GetString("label_source_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire Cible.
        /// </summary>
        internal static string label_target_directory {
            get {
                return ResourceManager.GetString("label_target_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix du language.
        /// </summary>
        internal static string language_choice {
            get {
                return ResourceManager.GetString("language_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix du type de log.
        /// </summary>
        internal static string log_type_choice {
            get {
                return ResourceManager.GetString("log_type_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix de la musique.
        /// </summary>
        internal static string music_choice {
            get {
                return ResourceManager.GetString("music_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers prioritaires.
        /// </summary>
        internal static string priority_files {
            get {
                return ResourceManager.GetString("priority_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix du logiciel métier.
        /// </summary>
        internal static string select_business_app {
            get {
                return ResourceManager.GetString("select_business_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution séquentielle.
        /// </summary>
        internal static string sequential_execution {
            get {
                return ResourceManager.GetString("sequential_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille Limite.
        /// </summary>
        internal static string size_limit {
            get {
                return ResourceManager.GetString("size_limit", resourceCulture);
            }
        }
    }
}
